
- name: Spark requisites
  hosts: all

  tasks:
    # - name: Print all available facts
    #   ansible.builtin.debug:
    #     var: ansible_facts


    - name: Install Java
      apt:
        name: default-jre
      become: yes

    - name: Extract spark
      ansible.builtin.unarchive:
        src: /vagrant/spark-3.1.2-bin-hadoop3.2.tgz
        dest: /home/vagrant
        remote_src: yes

    - name: Set SPARK_HOME 
      lineinfile:
        path: /home/vagrant/.bashrc
        regexp: "export SPARK_HOME=/home/vagrant/spark-3.1.2-bin-hadoop3.2"
        line: export SPARK_HOME=/home/vagrant/spark-3.1.2-bin-hadoop3.2

    - name: Set SPARK_LOCAL_IP
      lineinfile:
        path: /home/vagrant/.bashrc
        regexp: "export SPARK_LOCAL_IP=192.168.123.4"
        line: export SPARK_LOCAL_IP=192.168.123.4

