- name: Livy requisites
  hosts: master_node
  tasks:
    - name: Install unzip
      apt:
        name: unzip
      become: yes

- name: Spark requisites
  hosts: all
  tasks:
    - name: Install Java
      apt:
        name: default-jre
      become: yes

    - name: Extract spark
      ansible.builtin.unarchive:
        src: /vagrant/spark-3.1.2-bin-hadoop3.2.tgz
        dest: /home/vagrant
        remote_src: yes

    - name: Set SPARK_HOME 
      lineinfile:
        path: /home/vagrant/.bashrc
        regexp: "export SPARK_HOME=/home/vagrant/spark-3.1.2-bin-hadoop3.2"
        line: export SPARK_HOME=/home/vagrant/spark-3.1.2-bin-hadoop3.2

    - name: Set SPARK_LOCAL_IP
      lineinfile:
        path: /etc/profile
        regexp: "export SPARK_LOCAL_IP={{ spark_local_ip[ansible_hostname] }}"
        line: "export SPARK_LOCAL_IP={{ spark_local_ip[ansible_hostname] }}"
      become: yes

    - name: Remove /etc/hosts
      file:
        state: absent
        path: /etc/hosts
      become: yes

    - name: Set /etc/hosts
      blockinfile:
        path: /etc/hosts
        state: present
        block: |
          {{ item.ip }} {{ item.name }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
        backup: yes
        create: yes
        mode: "444"
      loop: "{{ vm_configs }}"
      become: yes
